---
- name: descargar Oracle JDK
  command: curl -L -H 'Cookie:oraclelicense=accept-securebackup-cookie' -o {{ jdk_file }} {{ jdk_url }}
  args:
    chdir: "{{ jdk_download_path }}"

- name: instalar Oracle JDK
  command: rpm --force -Uvh {{ jdk_file }}
  args:
    chdir: "{{ jdk_download_path }}"

- name: actualizar /etc/alternatives
  script: ../files/update-alternatives.sh "{{ jdk_version }}"

- name: limpieza
  file: state=absent path="{{ jdk_download_path }}/{{ jdk_file }}"